src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $username = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Book::class, cascade:["All"], orphanRemoval:true)]
    private Collection $books;

    #[ORM\Column(nullable: true)]
    private ?int $nb_books = null;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        
        return(string)$this->getUsername();
    
    }

    public function getNbBooks(): ?int
    {
        return $this->nb_books;
    }

    public function setNbBooks(?int $nb_books): static
    {
        $this->nb_books = $nb_books;

        return $this;
    }


}

src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\Column]
    private ?int $ref = null;

    #[ORM\Column(length: 20)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $publicationdate = null;

    #[ORM\Column]
    private ?bool $published = null;

    #[ORM\ManyToOne(inversedBy: 'books')]
    private ?Author $author = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $category = null;

    public function getRef(): ?int
    {
        return $this->ref;
    }

    public function setRef(string $ref): static
    {
        $this->ref=$ref;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getPublicationdate(): ?\DateTimeInterface
    {
        return $this->publicationdate;
    }

    public function setPublicationdate(\DateTimeInterface $publicationdate): static
    {
        $this->publicationdate = $publicationdate;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): static
    {
        $this->published = $published;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;
use App\Entity\Author;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ref')
            ->add('title')
            ->add('category', ChoiceType::class, [
                'choices' => [
                    'Science-Fiction' => 'Science-Fiction',
                    'Mystery' => 'Mystery',
                    'Autobiography' => 'Autobiography',
                ],
            ])
            ->add('publicationdate')
            ->add('published')
            ->add('author')
            ->add('Save',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Controller\AuthorController;
use App\Repository\AuthorRepository;
use App\Entity\Author;
use App\Form\AuthorType;
use App\Form\SearchType;
use App\Repository\BookRepository;
use App\Entity\Book;
use App\Form\BookType;
use Doctrine\Persistence\ManagerRegistry;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BookController extends AbstractController
{
    #[Route('/book', name: 'app_book')]
    public function index(): Response
    {
        return $this->render('book/index.html.twig', [
            'controller_name' => 'BookController',
        ]);
    }

    #[Route('/showbook', name: 'app_showbook')]
    public function showbook(BookRepository $bookRepository, Request $req): Response
    {
        $book = $bookRepository->findAll();
        
        
        $form = $this->createForm(SearchType::class);
        $form->handleRequest($req);
        $nbcategory =$bookRepository->sommescifi();

        if($form->isSubmitted()) {
            $data = $form->get('ref')->getData();
            $book = $bookRepository->searchbyref($data);

            return $this->renderForm('book/showbook.html.twig', [
               
                'book' => $book,
                'f' => $form,
                'nbcategory' => $nbcategory
            ]);
        }
    return $this->renderForm('book/showbook.html.twig', [
        'book' => $book,
        'f' => $form,
        'nbcategory' => $nbcategory
    ]);

    }

    #[Route('/showbookasc', name: 'app_showbookasc')]
    public function showbookasc(BookRepository $bookRepository): Response
    {
        
        $book = $bookRepository->orderbyauthor();

        return $this->render('book/showbookasc.html.twig', [
            'book' => $book
        ]);
    }

    #[Route('/showlistdate', name: 'app_showlistdate')]
    public function showlistdate(BookRepository $bookRepository): Response
    {
        
        $book = $bookRepository->listedate();

        return $this->render('book/showlistdate.html.twig', [
            'book' => $book
        ]);
    }



    #[Route('/showlistpublie', name: 'app_showlistpublie')]
    public function listepublie(BookRepository $bookRepository): Response
    {
        
        $book = $bookRepository->listepublie();

        return $this->render('book/showlistpublie.html.twig', [
            'book' => $book
        ]);
    }



    
    #[Route('/addbookform', name: 'app_addbookform')]
    public function addbookform(ManagerRegistry $managerRegistry, Request $request): Response
    {
        $em = $managerRegistry->getManager();
        $book = new Book();

        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() and $form->isValid()) {

           

            $em->persist($book);
            $em->flush();

            return $this->redirectToRoute('app_showbook'); // Replace 'app_book' with the appropriate route name

        }
        

        return $this->renderForm('book/addbookform.html.twig', [
            'f' => $form
        ]);
    }

    #[Route('/editbookform/{id}', name: 'app_editbookform')]
    public function editbookform($id, ManagerRegistry $managerRegistry, BookRepository $bookRepository, Request $req): Response
    {
        $em=$managerRegistry->getManager();
        $dataid=$bookRepository->find($id);
        $form=$this->createForm(bookType::class,$dataid);
        $form->handleRequest($req);

        if($form->isSubmitted() and $form->isValid())
        {
            $em->persist($dataid);
            $em->flush();
            return $this->redirectToRoute('app_showbook');
             
        }


        return $this->renderForm('book/editbookform.html.twig', [
            'x'=>$form
        ]);
    }

    #[Route('/deletebook/{id}', name: 'app_deletebook')]
    public function deletedeletebook($id,ManagerRegistry $managerRegistry,BookRepository $bookRepository ): Response
    {
        $em=$managerRegistry->getManager();
        $dataid=$bookRepository->find($id);
        $em->remove($dataid);
        $em->flush();

        return $this->redirectToRoute('app_showbook');

       
    }

    #[Route('/bookdetails/{id}', name: 'app_bookdetails')]
    public function bookdetails($id, BookRepository $bookRepository): Response
    {
        $book = $bookRepository->find($id);
        return $this->render('book/bookdetails.html.twig', [
            'book' => $book
        ]);
    }






    



}

templates/book/addbookform.html.twig
{{form(f)}}

templates/book/bookdetails.html.twig
Title: {{ book.title }} <br>
Category: {{ book.category }} <br>
Author: {{ book.author.username }} <br>
Number of books: {{ book.author.nbBooks }} <br>
Publication: {{ book.publicationDate | date('Y-m-d') }}

templates/book/editbookform.html.twig
{{form(x)}}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/mdkhe/OneDrive/Desktop/symfony/FirstProject/src/Controller/BookController.php'|file_link(0) }}">src/Controller/BookController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/mdkhe/OneDrive/Desktop/symfony/FirstProject/templates/book/index.html.twig'|file_link(0) }}">templates/book/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/book/showbook.html.twig
<html>
    <body>
        <h1>List of published books</h1>

       {{form_start(f)}}
       {{form_label(f.ref)}}
       {{form_widget(f.ref)}}
       {{form_end(f)}}
       

        <table border="4">
            <tr>
                <td>ID</td>
                <td>title</td>
                <td>category</td>
                <td>publication</td>
                <td>published</td>
                
                <td>author </td>
                <td>Action</td>
                <td>Delete</td>
                
            </tr>
            {% set total = 0 %} 
            {% set total1 = 0 %} 
            {% for a in book %}
                <tr>
                    <td>{{a.ref}}</td>
                    <td>{{a.title}}</td>
                    <td>{{a.category}}</td>
                    <td>{{a.publicationDate|date('Y-m-d')}}</td>
                    <td>{{a.published ? 'true' : 'false'}}</td>
                    
                    <td>{{a.author.username}}</td>
                    <td><a href="{{ path('app_editbookform', {'id': a.ref}) }}">Edit</a></td>
                    <td><a href="{{ path('app_deletebook', {'id': a.ref}) }}">Delete</a></td>
                   
                    
                </tr>
                {% if a.published %}
                    {% set total = total + 1 %} 
                {% endif %}

                {% if not a.published %}
                    {% set total1 = total1 + 1 %} 
                {% endif %}

            {% endfor %}
        </table>
        <p>number of books with Science fiction category :  {{nbcategory}}</p>
        
        <a href="{{ path('app_showbookasc') }}"><button>Sort by Author</button></a>
        <a href="{{ path('app_showlistpublie') }}"><button>Livres publiés avant l’année 2023 dont l’auteur a plus de 35
            livres</button></a>


        {% if total > 0 %}
            Number of published books: {{ total }} <br>
        {% else %}
            No published books found.
        {% endif %}

        {% if total1 > 0 %}
            Number of unpublished books: {{ total1 }}
        {% else %}
            No unpublished books found.
        {% endif %}

        <br>
        <a href="{{ path('app_addbookform') }}"><button>Create New Book</button></a>
        <a href="{{ path('app_showlistdate') }}"><button>Show liste date between 2014 and 2018</button></a>




    </body>
</html>

templates/book/showbookasc.html.twig
<html>
    <body>
        <h1>List of published books</h1>
        <table border="4">
            <tr>
                <td>ID</td>
                <td>title</td>
                <td>publication</td>
                <td>published</td>
                
                <td>author </td>
                <td>Action</td>
                <td>Delete</td>
                
            </tr>
            {% set total = 0 %} 
            {% set total1 = 0 %} 
            {% for a in book %}
                <tr>
                    <td>{{a.ref}}</td>
                    <td>{{a.title}}</td>
                    <td>{{a.publicationDate|date('Y-m-d')}}</td>
                    <td>{{a.published ? 'true' : 'false'}}</td>
                    
                    <td>{{a.author.username}}</td>
                    <td><a href="{{ path('app_editbookform', {'id': a.ref}) }}">Edit</a></td>
                    <td><a href="{{ path('app_deletebook', {'id': a.ref}) }}">Delete</a></td>
                   
                    
                </tr>
                {% if a.published %}
                    {% set total = total + 1 %} 
                {% endif %}

                {% if not a.published %}
                    {% set total1 = total1 + 1 %} 
                {% endif %}

            {% endfor %}
        </table>

        {% if total > 0 %}
            Number of published books: {{ total }} <br>
        {% else %}
            No published books found.
        {% endif %}

        {% if total1 > 0 %}
            Number of unpublished books: {{ total1 }}
        {% else %}
            No unpublished books found.
        {% endif %}

        <br>
        <a href="{{ path('app_addbookform') }}"><button>Create New Book</button></a>
        



    </body>
</html>

templates/book/showlistdate.html.twig
<html>
    <body>
        <h1>List of published books</h1>

       

        <table border="4">
            <tr>
                <td>ID</td>
                <td>title</td>
                <td>category</td>
                <td>publication</td>
                <td>published</td>
                
                <td>author </td>
                <td>Action</td>
                <td>Delete</td>
                
            </tr>
            {% set total = 0 %} 
            {% set total1 = 0 %} 
            {% for a in book %}
                <tr>
                    <td>{{a.ref}}</td>
                    <td>{{a.title}}</td>
                    <td>{{a.category}}</td>
                    <td>{{a.publicationDate|date('Y-m-d')}}</td>
                    <td>{{a.published ? 'true' : 'false'}}</td>
                    
                    <td>{{a.author.username}}</td>
                    <td><a href="{{ path('app_editbookform', {'id': a.ref}) }}">Edit</a></td>
                    <td><a href="{{ path('app_deletebook', {'id': a.ref}) }}">Delete</a></td>
                   
                    
                </tr>
                {% if a.published %}
                    {% set total = total + 1 %} 
                {% endif %}

                {% if not a.published %}
                    {% set total1 = total1 + 1 %} 
                {% endif %}

            {% endfor %}
        </table>        
        <a href="{{ path('app_showbookasc') }}"><button>Sort by Author</button></a>
        <a href="{{ path('app_showlistpublie') }}"><button>Livres publiés avant l’année 2023 dont l’auteur a plus de 35
            livres</button></a>


        {% if total > 0 %}
            Number of published books: {{ total }} <br>
        {% else %}
            No published books found.
        {% endif %}

        {% if total1 > 0 %}
            Number of unpublished books: {{ total1 }}
        {% else %}
            No unpublished books found.
        {% endif %}

        <br>
        <a href="{{ path('app_addbookform') }}"><button>Create New Book</button></a>
        



    </body>
</html>

templates/book/showlistpublie.html.twig
<html>
    <body>
        <h1>List of published books</h1>

     
        <table border="4">
            <tr>
                <td>ID</td>
                <td>title</td>
                <td>publication</td>
                <td>published</td>
                
                <td>author </td>
                <td>Author nb books</td>
                <td>Action</td>
                <td>Delete</td>
                
            </tr>
            {% set total = 0 %} 
            {% set total1 = 0 %} 
            {% for a in book %}
                <tr>
                    <td>{{a.ref}}</td>
                    <td>{{a.title}}</td>
                    <td>{{a.publicationDate|date('Y-m-d')}}</td>
                    <td>{{a.published ? 'true' : 'false'}}</td>
                    
                    <td>{{a.author.username}}</td>
                    <td>{{a.author.getNbBooks()}}</td>
                    <td><a href="{{ path('app_editbookform', {'id': a.ref}) }}">Edit</a></td>
                    <td><a href="{{ path('app_deletebook', {'id': a.ref}) }}">Delete</a></td>
                   
                    
                </tr>
                {% if a.published %}
                    {% set total = total + 1 %} 
                {% endif %}

                {% if not a.published %}
                    {% set total1 = total1 + 1 %} 
                {% endif %}

            {% endfor %}
        </table>
        <a href="{{ path('app_showbookasc') }}"><button>Sort by Author</button></a>

        {% if total > 0 %}
            Number of published books: {{ total }} <br>
        {% else %}
            No published books found.
        {% endif %}

        {% if total1 > 0 %}
            Number of unpublished books: {{ total1 }}
        {% else %}
            No unpublished books found.
        {% endif %}

        <br>
        <a href="{{ path('app_addbookform') }}"><button>Create New Book</button></a>
        



    </body>
</html>